### PR TITLE
.travis.yml does not cache dependencies

### PR DESCRIPTION
**Pull request by chenzhang22**
Travis CI can cache content that does not often change, to speed up your build process.

### CODE REVIEW

**Comment by ralf0131** [comment]
Hi, Please sign the CLA first ~

**Comment by chenzhang22** [comment]
签了

**Review by ralf0131 — APPROVED** [review]
LGTM

**Comment by ralf0131** [comment]
Sorry the system shows you are not signed yet. Your account should match the name and email in your commit message.

**Comment by ralf0131** [comment]
```
Commits on Aug 2, 2021
add cache

Your Name committed on Aug 2
```

This commit is committed by `Your Name` and is not signed.
I suggest recommit with a correct name and email.

**Pull request closed without merging**
